# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 586d070cf05e3cca5f0722ed95b3383aaa030ecfbac799fc378cfeb687635bdc9e594a72cbf99cdd1f886369eacf9ee487341450e26b7ab47d8ac1953801c369

test:
  secret_key_base: f1ca0fc882cfe649db771069c12664a6edb657fde59bc11934391a24404e440d7dc91cbafd9b0493623cb5b2b408499a6edc1228b8263fdc32476b2c572b2ba7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
